### PR TITLE
fix up display pinning for sunton 7 inch

### PR DESCRIPTION
**Pull request by markusdd**
now that I have the display actually in hand and my program up I tested it and realized that the pinning was completely off.
The backlight pin was an error on my part, but the rgb pinout in the schematic and what the tasmota doc says how they should be listed is completely different.

I kind of derived the pattern from the sunton 5 inch and now it works, but it first takes some pins form one color, then a few from another, it seems completely mixed. .

### CODE REVIEW

**Comment by markusdd** [comment]
To explain what I mean, this is the doc:
grafik

The Sunton 5 inch has this schematic:
grafik

And the pattern in the autoconf template for the 5 inch is this:

`:H,ST7262,800,480,16,RGB,40,41,39,42,2,15,16,4,45,48,47,21,14,8,3,46,9,1,5,6,7,14`

If you compare this to the given schematic, you see that after the backlight pin (2) it starts with G5, G6, G7 (so ignoring the lower tied ones this would equate to G5, G4, G3. But the docs say first comes blue from b0 to b5. You can trace this for all the other pins, it's a complete mix.

With my original template, after fixing the backlight, it worked, but color were completely off and my background had stripes.

I'm happy it works now by copying the pattern from the 5inch and just adapting the pin numbers it works, but I do not know why to be honest.

**Comment by markusdd** [comment]
@Jason2866 I see you are the one who contributed the 5 inch autoconf template. can you shed some light on how you figured that out?

**Comment by Jason2866** [comment]
Sorry, just provided the already existing setup here.

**Comment by markusdd** [comment]
ok thank you!

 when you say 'already existing' - where did you have it from?

**Comment by Jason2866** [comment]
https://github.com/arendst/Tasmota/pull/17414

**Comment by markusdd** [comment]
@gemu2015 can you possibly shed some light on this why the RGB pin assignment in the display.ini does not match the docs at all for the color pins? VSYNC, HSYNC etc are all matching 1:1, but I have no idea how you figured out the RGB assignment.

**Comment by gemu2015** [comment]
@markusdd 
i bought this display from makerfabs and adapted universal driver for rgb displays and particular this one.  the display.ini for st7262 is definitely working with this display. it was sold out very soon after i bought it and is sold out until today. i do not know about other similar displays pin assignments.  they may well be different.  also possible that the docs may still have bugs 
anyhow RGB displays have a 16 bit color mode and should give a picture even with false colors.
in general RGB displays are very slow and not much recommended for LVGL and such.
the display hardware has no display RAM und such the CPU must hold the picture in a picture buffer that has to be transferred completely 50 times per second to the display.
this happens via DMA from PSRAM.  since PSRAM is SPI bus together with CPU Flash memory, this slows down the CPU considerably.

**Comment by markusdd** [comment]
my question was more specifically while the docs say to give the RGB pins in order, the real order that works for correct colors is a wild mixture. (I had the exact problem you mentioned, everything was displaying but colors were wild)

I have used this display with LVGL and had good success by disabling usage of the PSRAM.  Sure it's not necessarily blazing fast but it makes for avery nice large control and status screen. More than enough to display a few light switches etc.

Are you aware of non-RGB displays of this size which are less resource-heavy on the CPU?

**Comment by Jason2866** [comment]
> Are you aware of non-RGB displays of this size which are less resource-heavy on the CPU?

Parallel driven ones. https://github.com/arendst/Tasmota/pull/16713

**Comment by markusdd** [comment]
ok, but this is tiny comparatively.

and resistive touch is an absolute no-go xD

**Comment by Jason2866** [comment]
Did add a second one

**Comment by Jason2866** [comment]
A esp32-s3 is just a too low end MCU to drive a bigger display fast.

**Comment by markusdd** [comment]
ok this is better, still only 3.5 unfortunately.

but as said, the 7 inch actually works great when running the display buffer from RAM and not PSRAM.
It's not blazing fast, but for a relatively static light control panel it is good enough.

and pertaining to this PR: with the fixed color pins in the display.ini also the colors work :D
grafik

**Pull request merged**
