### PR TITLE
moved the file to root, rewritten using os.walk

### PR DESCRIPTION
**Pull request by jziolkowski**

### CODE REVIEW

**Comment by s-hadinger** [comment]
Running the script from the root of the repo, I get this error:

```python3 gen.py
Traceback (most recent call last):
  File "gen.py", line 11, in <module>
    a, _, arch, board = board_dir.split('/')
ValueError: not enough values to unpack (expected 4, got 2)```

**Comment by s-hadinger** [comment]
Also, you must change the current dir before calling `myzip.write(filepath, file)` so that the archive contains a filename without any parent directories.

**Comment by s-hadinger** [comment]
That's why I wanted to avoid `os.walk()` in the first place, because it brings a lot of noise:
```
...
('./raw', ['esp32c3', 'esp32', 'esp32s2'], ['.DS_Store', 'gen.py'])
('./raw/esp32c3', ['AI_Thinker_12F'], ['.DS_Store'])
('./raw/esp32c3/AI_Thinker_12F', [], ['init.bat'])
('./raw/esp32', ['m5Stack_Core2', 'Olimex_POE', 'M5Stack_Fire'], ['.DS_Store'])
('./raw/esp32/m5Stack_Core2', [], ['display.ini', 'preinit.be', 'init.bat'])
('./raw/esp32/Olimex_POE', [], ['init.bat'])
('./raw/esp32/M5Stack_Fire', [], ['display.ini', 'init.bat'])
('./raw/esp32s2', ['DevKitM-1'], ['.DS_Store'])
('./raw/esp32s2/DevKitM-1', [], ['init.bat'])```

**Comment by s-hadinger** [comment]
You also removed the test `startswith('.')` which was meant to not include `.DS_Store` files in the archive

**Comment by jziolkowski** [comment]
> Also, you must change the current dir before calling `myzip.write(filepath, file)` so that the archive contains a filename without any parent directories.

No. This is why I added the second parameter to myzip.write to assing a new, proper name

**Comment by jziolkowski** [comment]
> You also removed the test `startswith('.')` which was meant to not include `.DS_Store` files in the archive

I did not have these files when making them locally. Might be a Mac thing?

**Comment by jziolkowski** [comment]
> That's why I wanted to avoid `os.walk()` in the first place, because it brings a lot of noise:
> 
> ```
> ...
> ('./raw', ['esp32c3', 'esp32', 'esp32s2'], ['.DS_Store', 'gen.py'])
> ('./raw/esp32c3', ['AI_Thinker_12F'], ['.DS_Store'])
> ('./raw/esp32c3/AI_Thinker_12F', [], ['init.bat'])
> ('./raw/esp32', ['m5Stack_Core2', 'Olimex_POE', 'M5Stack_Fire'], ['.DS_Store'])
> ('./raw/esp32/m5Stack_Core2', [], ['display.ini', 'preinit.be', 'init.bat'])
> ('./raw/esp32/Olimex_POE', [], ['init.bat'])
> ('./raw/esp32/M5Stack_Fire', [], ['display.ini', 'init.bat'])
> ('./raw/esp32s2', ['DevKitM-1'], ['.DS_Store'])
> ('./raw/esp32s2/DevKitM-1', [], ['init.bat'])```
> ```

Not noise, just different approach.

First, like I wrote on discord, remove the gen.py from ./raw, for some reason git didn't notice the change.

Ignoring .ds_store is trivial, I'll amend the PR.

**Comment by jziolkowski** [comment]
> Running the script from the root of the repo, I get this error:
> 
> ```python
> Traceback (most recent call last):
>   File "gen.py", line 11, in <module>
>     a, _, arch, board = board_dir.split('/')
> ValueError: not enough values to unpack (expected 4, got 2)```
> ```

this is because gen.py and .ds_Store is present.

**Comment by s-hadinger** [comment]
> > Also, you must change the current dir before calling `myzip.write(filepath, file)` so that the archive contains a filename without any parent directories.
> 
> No. This is why I added the second parameter to myzip.write to assing a new, proper name

Thanks got it.

> > Running the script from the root of the repo, I get this error:
> > ```python
> > Traceback (most recent call last):
> >   File "gen.py", line 11, in <module>
> >     a, _, arch, board = board_dir.split('/')
> > ValueError: not enough values to unpack (expected 4, got 2)```
> > ```
> 
> this is because gen.py and .ds_Store is present.

I would like the script to be resilient to unexpected files. It should ignore non-directories when scanning, and include only files not starting with '.' in ZIP. Thanks !

**Comment by jziolkowski** [comment]
> > > Also, you must change the current dir before calling `myzip.write(filepath, file)` so that the archive contains a filename without any parent directories.
> > 
> > 
> > No. This is why I added the second parameter to myzip.write to assing a new, proper name
> 
> Thanks got it.
> 
> > > Running the script from the root of the repo, I get this error:
> > > ```python
> > > Traceback (most recent call last):
> > >   File "gen.py", line 11, in <module>
> > >     a, _, arch, board = board_dir.split('/')
> > > ValueError: not enough values to unpack (expected 4, got 2)```
> > > ```
> > 
> > 
> > this is because gen.py and .ds_Store is present.
> 
> I would like the script to be resilient to unexpected files. It should ignore non-directories when scanning, and include only files not starting with '.' in ZIP. Thanks !

I've already found a way to make os.walk ignore dot-files, will update PR later

**Comment by s-hadinger** [comment]
Thanks but I'm still getting 

```
Traceback (most recent call last):
  File "gen.py", line 14, in <module>
    a, _, arch, board = board_dir.split('/')
ValueError: not enough values to unpack (expected 4, got 2)
```

When printing values, `board_dir` value is `./raw` which yields only 2 elements, not 4

**Pull request merged**
